apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yrpetclinic-deploy
  labels:
    app.kubernetes.io/name: yrpetclinic-deploy
    app.kubernetes.io/part-of: yrpetclinic-deploy-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yrpetclinic-deploy